name: Build & Publish to ECR

on:
  push:
    branches:
      - main   # 1. Netleştir: hangi branch?

jobs:
  version-and-publish:
    runs-on: ubuntu-latest
    env:
      ECR_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REGION:  ${{ secrets.AWS_REGION }}
      ECR_REPO:    ${{ secrets.ECR_REPO_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # tüm commit geçmişi gerekebilir versiyon commit’i için

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Bump patch version
        run: |
          NEW_VER=$(npm version patch --no-git-tag-version)
          echo "VERSION=$NEW_VER" >> $GITHUB_OUTPUT

      - name: Commit version bump
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: bump version to ${{ steps.bump.outputs.VERSION }}"
          add: 'package.json, package-lock.json'

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: |
          IMAGE_URI=${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPO}:${{ steps.bump.outputs.VERSION }}
          docker build -t $IMAGE_URI .
          # Optional: latest etiketi de
          docker tag $IMAGE_URI ${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPO}:latest

      - name: Push to ECR
        run: |
          docker push ${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPO}:${{ steps.bump.outputs.VERSION }}
          docker push ${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPO}:latest

      - name: Output image URI
        run: echo "Image published: ${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPO}:${{ steps.bump.outputs.VERSION }}"
